import pandas as pd

def annotate_feature_found(clusters_df: pd.DataFrame, sample_name, sample_type):
    """
    Adds a column indicating whether an intensity value is detected for the feature.
    Returns the input DataFrame with the additional column.

    :param clusters_df: DataFrame containing all clusters generated by the IsoGroup's untargeted mode.
    :param sample_name: Name of the sample use for enhancer
    :param sample_type: Type of the sample (unlabeled or labeled)
    """

    new_col = f"Found in {sample_type} sample"
    clusters_df.loc[:, new_col] = None

    clusters_df.loc[(clusters_df["sample"] == sample_name) & (clusters_df["Intensity"] == 0), new_col] = "No" #all features with zero intensity
    clusters_df.loc[~((clusters_df["sample"] == sample_name) & (clusters_df["Intensity"] == 0)), new_col] = "Yes"

    return clusters_df


def calculate_m1_m0_ratio(clusters_df:pd.DataFrame, sample_name):
    """
    Calculates the M1/M0 intensity ratio and adds it as a new column.
    Returns the input DataFrame with the additional column.

    :param clusters_df: DataFrame containing all clusters generated by the IsoGroup's untargeted mode.
    :param sample_name: Name of the sample use for enhancer
    :param sample_type: Type of the sample (unlabeled or labeled)
    """

    sample_subset = clusters_df.loc[clusters_df["sample"]==sample_name] 

    new_col = "Mx+1/Mx ratio"

    numerateur = sample_subset[sample_subset["Isotopologue"] == "Mx+1"].set_index("ClusterID")["Intensity"]
    denominateur = sample_subset[sample_subset["Isotopologue"] == "Mx"].set_index("ClusterID")["Intensity"]
    df_result = (numerateur.div(denominateur)).rename(new_col)

    sample_subset = sample_subset.merge(df_result, on="ClusterID", how="left")
    sample_subset.loc[sample_subset[new_col].isna() | (sample_subset[new_col] == 0), new_col] = "ND"
    return sample_subset

# if __name__ == "__main__":
   
#     # data_test = pd.read_csv(r"C:\Users\kouakou\Documents\IsoGroup_test\test_filter\donnee\dataset_test_2_res_untarg\dataset_test_2.clusters_before_filter.tsv", sep="\t")
#     data_test = pd.read_csv(r"C:\Users\kouakou\Documents\IsoGroup_test\these_NBU_Data\use_case_XCMS_data_res\XCMS_data.clusters.tsv", sep="\t")
#     annotate_feature_found(data_test, "C12_WT_3", "unlabeled")
#     calculate_m1_m0_ratio(data_test, "C12_WT_3")
  
############################################################################
# def potential_m0_filter(df: pd.DataFrame, sample_name) -> pd.DataFrame: 
#     """ 
#     Filter the clusters to identify potential M0 features based on the minimum intensity in the "Mx" isotopologue group. 
#     #A optimiser 
#     """

#     # filtered_df = df.drop(df[(df["sample"] == sample_name) & (df["Intensity"]==0)].index)
#     filtered_df = df
#     df_mx = filtered_df[filtered_df["Isotopologue"] == "Mx"]

#     # df_grouped = df_mx.groupby(["ClusterID", "sample"]).min()

#     for cluster_id in df_mx["ClusterID"].unique():
#         df_cluster = df_mx[df_mx["ClusterID"] == cluster_id]
#         for feature_id in df_cluster["FeatureID"].unique():
#             df_feature = df_cluster[(df_cluster["FeatureID"] == feature_id)]
#             value_min = df_feature["Intensity"].min()
#             if (df_feature.loc[df_feature["sample"] == sample_name, "Intensity"] == value_min).any():
#                 filtered_df.loc[df_feature.index, "M0 found"] = "No"
#             else:
#                 filtered_df.loc[df_feature.index, "M0 found"] = "Yes"
    
#     return filtered_df