"""
This script contains functions designed to improve cluster annotation using labeled sample.
"""
import numpy as np
import pandas as pd

def annotate_feature_found(clusters_df: pd.DataFrame, sample_name):
    """
    Adds a column indicating whether an intensity value is detected for the feature.
    Returns the input DataFrame with the additional column.

    :param clusters_df: DataFrame containing all clusters generated by the IsoGroup's untargeted mode.
    :param sample_name: Name of the sample use for enhancer
    """

    new_col = f"Found in fully labeled sample ({sample_name})"
    
    not_found_list =   clusters_df.loc[(clusters_df["sample"] == sample_name) & (clusters_df["Intensity"] == 0), "FeatureID"].to_list()
    is_found_list = clusters_df.loc[~((clusters_df["sample"] == sample_name) & (clusters_df["Intensity"] == 0)), "FeatureID"].to_list()
    
    condition = [
        clusters_df["FeatureID"].isin(not_found_list),
        clusters_df["FeatureID"].isin(is_found_list)
    ]
    
    value = ["No",
             "Yes"]
    
    clusters_df[new_col] = np.select(condition, value, default=None)

    return clusters_df

############################################################################
# def potential_m0_filter(df: pd.DataFrame, sample_name) -> pd.DataFrame: 
#     """ 
#     Filter the clusters to identify potential M0 features based on the minimum intensity in the "Mx" isotopologue group. 
#     #A optimiser 
#     """

#     # filtered_df = df.drop(df[(df["sample"] == sample_name) & (df["Intensity"]==0)].index)
#     filtered_df = df
#     df_mx = filtered_df[filtered_df["Isotopologue"] == "Mx"]

#     # df_grouped = df_mx.groupby(["ClusterID", "sample"]).min()

#     for cluster_id in df_mx["ClusterID"].unique():
#         df_cluster = df_mx[df_mx["ClusterID"] == cluster_id]
#         for feature_id in df_cluster["FeatureID"].unique():
#             df_feature = df_cluster[(df_cluster["FeatureID"] == feature_id)]
#             value_min = df_feature["Intensity"].min()
#             if (df_feature.loc[df_feature["sample"] == sample_name, "Intensity"] == value_min).any():
#                 filtered_df.loc[df_feature.index, "M0 found"] = "No"
#             else:
#                 filtered_df.loc[df_feature.index, "M0 found"] = "Yes"
    
#     return filtered_df